### ISSUE TITLE
[Help] After Inject a class WebSocketServerDemo with static method, I can't use it!

### ISSUE THREAD

**Issue by huhuang03** [sailro/Reflexil#100]
In c# .Net Reflector

I inject a class named `WebSocketServerDemo` with a public static method `start()`.

After do this, I want call it, but when I click compile, It shows
`Error Number: CS0570, Error message: current language doesn't support "WebSocketServerDemo.start()"`

I'm a newer to c# and reflexil. Can you tell me why! Thanks

**Comment by sailro** [comment]
Depends on the .NET Reflector you are using. Newer versions are able to refresh the object model after injection. For older ones, save your assembly after modifying it, then reload it.
