### ISSUE TITLE
about the strong name sha256

### ISSUE THREAD

**Issue by omidfz** [sailro/Reflexil#102]
hi again,
about the double signing not code signing with sha256 you have not this menu on reflixil to changing or....
it has only sha1 ,None , Reserved.
and if i want to change or new public key for sha256 ,here is no option menu...
![1](https://cloud.githubusercontent.com/assets/6241917/26093784/899bda56-3a2c-11e7-9c1c-83b04bde3c5e.jpg)
![2](https://cloud.githubusercontent.com/assets/6241917/26093909/016ec5e8-3a2d-11e7-9fc0-59a946b5a3e5.jpg)

**Comment by omidfz** [comment]
hi  again,
is there any chance to adding item of  SHA256  algorithm to new version of reflexil ?

**Comment by sailro** [comment]
This is not the same thing.

https://github.com/sailro/Reflexil/issues/101
