### ISSUE TITLE
reflexil is unable to save this assembly

### ISSUE THREAD

**Issue by SergeyDC4** [sailro/Reflexil#105]
In the function necessary to me passed arguments and the link to the function necessary to me - now my dll is not saved

https://s10.postimg.org/xn2dz6e6x/image.png
https://s17.postimg.org/plfppldzz/image.png

**Comment by sailro** [comment]
Could you translate the error message ? And give me more details please.

**Comment by Sub-7** [comment]
Error message say: "The specified argument is in the range of the valid range."

**Comment by sailro** [comment]
Seems that you are trying to call a function without the proper arguments. You should perhaps use "Replace All with code" to properly understand what you are doing (and with compiler error messages)

**Comment by nimeshvaghasiya** [comment]
@sailro @Solotov Me too. I got same error message without any change to dll or change in code in boolean function
"reflexil is unable to save this assembly : value cannot be null"
