### ISSUE TITLE
Patching "Assembly-CSharp.dll" has no effect in the game

### ISSUE THREAD

**Issue by Sub-7** [sailro/Reflexil#106]
First of all thank you for your great work Sebastien,

**Problem:**
I have edited, verified and stored the "Assembly-CSharp.dll", all without problems and error messages.
Replace the original file in "Assembly-CSharp-ORG.dll" and "Assembly-CSharp.Patched.dll" in Assembly-CSharp.dll in -> "Managed" folder.
I do not see any changes in the game!

Is the file loaded at all?
What am I doing wrong?

Is there any way to print "Hello World" on the screen in Unity? To test it at all.

![original](https://user-images.githubusercontent.com/30667941/28916467-95b7bc48-7842-11e7-9d4a-75db2bfb0a48.PNG)
![patch](https://user-images.githubusercontent.com/30667941/28916470-99b466de-7842-11e7-83c2-236d34963e68.PNG)

**Comment by Splamy** [comment]
Search for any `MonoBehaviour` class which you know will be instanced in the game.  
Add or modify the `Update` method.
In it call the static GUI.Label method (see: https://docs.unity3d.com/ScriptReference/GUI.Label.html)
Should look smth like this (untested):
ldc.r4 0
ldc.r4 0
ldc.r4 100
ldc.r4 100
newobj Rect.ctor(float,float,float,float)
ldstr "helloworld"
call GUI.Label(Rect, string)

**Comment by sailro** [comment]
I also made a video to demo how to patch a Unity game.
https://www.youtube.com/watch?v=fAHvevOFdbo

**Comment by Sub-7** [comment]
@Splamy Thx, so I have found you here at all.

In my case, SpiderAttackMoveControler is in the assembly-UnityScript,
CompileError: rigidbody undefined or something.

![error](https://user-images.githubusercontent.com/30667941/28964314-8fe94b5e-790c-11e7-9829-8bed8204f730.PNG)

[Managed.zip](https://github.com/sailro/Reflexil/files/1199956/Managed.zip)

**Comment by Splamy** [comment]
Just read what it says there.
`character` is a `Transform` and has no rigidbody attribute.
You should make something like `this.character.gameObject.GetComponent<RigidBody>()...`
also it's spelled `AddForce`.
Look up the unity manual (https://docs.unity3d.com/ScriptReference/Transform.html, https://docs.unity3d.com/ScriptReference/MonoBehaviour.html)
There is everthing you need.
You should get some Unity experience in generel before trying to modify unity assemblies. Unity is freely available and a easy to learn engine.

**Comment by sailro** [comment]
Seems that this is not a Reflexil question but a Unity one :)

Indeed using Reflexil requires that you are at ease with the technology you are trying to alter.

Closing this thread.
