### ISSUE TITLE
PEVerify Utility (peverify.exe) not found

### ISSUE THREAD

**Issue by Sub-7** [sailro/Reflexil#108]
**I get an error:**
"PEVerify Utility (peverify.exe) not found. Update your PATH environment variable or install .NET SDK"

Can not find anything
Which is .Net SDK is meant?
Do you have a link?

**System:**
W10
VS 2017
Reflector 9.2.609
Reflexil 2.1

**Comment by sailro** [comment]
PEverify is installed with Visual Studio.

You can download a standalone SDK like this one (but the following is not the latest)
https://www.microsoft.com/en-us/download/details.aspx?id=8279

**Comment by Sub-7** [comment]
This can not be installed under W10,
PEVerify.exe is also available in: 
C: \ Program Files (x86) \ Microsoft SDKs \ Windows \ v10.0A \ bin \ NETFX 4.6.1 Tools \ x64

PEverify.exe linked incorrectly? Where can I change this?

**Comment by AndrewSav** [comment]
@Sub-7 it need to be on your $path
