### ISSUE TITLE
Problem with injecting assembly

### ISSUE THREAD

**Issue by Crumbler** [sailro/Reflexil#109]
So I'm using ILSpy with Reflexil. I'm trying to save a .exe but I get a message "Reflexil is unable to save this assembly: Failed to resolve assembly:'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'" . When I try to inject a reference to this assembly I get  a message: "Unable to stream assembly to ILSpy. In case of item deletion make sure you removed all existing references".

**Comment by sailro** [comment]
You should also load this Newtonsoft assembly in ILSpy, so that the assembly resolver will be able to load the dependency.
