### ISSUE TITLE
Is it possible to use dnlib to modify mixed assemblies?

### ISSUE THREAD

**Issue by UlyssesWu** [sailro/Reflexil#11]
Hi,
  I want to modify managed parts of mixed assemblies, but since Mono.Cecil can not fully support mixed assemblies so currently we can't do that in Reflexil.
  I tried [dnlib](https://github.com/0xd4d/dnlib) and successfully added a (managed) method into a mixed assembly. Maybe Reflexil can use dnlib as another "Engine" ?

**Comment by sailro** [comment]
We have a important dependency on Mono.Cecil (and we have our custom fork). I don't know the work we need to achieve that, but it should be huge. Too huge i think.

**Comment by UlyssesWu** [comment]
Thanks for replying.
Yes, I have been trying to modify Reflexil to (partly) use dnlib, but I think this job is too hard for a green hand in coding :(
At least I think dnlib can do almost all works which Reflexil needs.
Just wish Mono.Cecil can support writing mixed assemblies someday!
