### ISSUE TITLE
How to pass current instance of the class as a parameter

### ISSUE THREAD

**Issue by zayyeh** [sailro/Reflexil#110]
Hi.

First of all, thanks so much for this wonderful tool. I figured out how to do almost everything what I need except this:

http://prntscr.com/gb94a0

It compiles successfully in my Microsoft Visual Studio project, but I can't figure out how to make Reflexil compile this. I'm pretty sure there is easy solution.

EDIT: EnemyBase class is public, but when I mouse over the class name in the compiler window, it shows that the class is internal. Not sure if it has anything to do with this issue.
UPD: Even with setting class as public, nothing changes.

**Comment by sailro** [comment]
Could you share your assembly + repro steps so I could have a look ?

**Comment by zayyeh** [comment]
Here is the link: https://www.dropbox.com/s/dz7ea2erqzuaquw/For_sailro.rar?dl=0
RAR contains two files: Assembly-CSharp.dll which is the game dll, and referenced to it CommunityMod.dll, which I compile my solution to.
Go to EnemyBase class in Assembly-CSharp.dll > TakeDamage(in32, Boolean) and try to just compile it without any changes.

While you are at it, there is another issue: I can't access class properties (i.e. Health, Effects), only values (i.e. health, effects). I suspect it could be related to the first issue. I'm missing something simple obviously.

**Comment by sailro** [comment]
My first comment after having a look at your assemblies, is that referenced assemblies are messed up. You probably used PostSharp to process the assembly or used an old Reflexil version.

The first thing is to correct duplicate references to the same assembly (mscorlib is referenced 3 times with distinct versions). Be sure to use the public key + version of the mscorlib.dll that is shipped with the Unity game.

**Comment by zayyeh** [comment]
So ideally Assembly-CSharp referenced assemblies should be unmodified with only one added reference to my DLL, and my DLL should target the same framework as main dll, and contain same references?

Here is the original game file, problem stays the same: https://www.dropbox.com/s/972ds2g0v79p54h/Original.rar?dl=0

**Comment by sailro** [comment]
If you remove stub factory methods in the code window like:  static BuildingPanel_Classes CreateNew() it is working properly.

**Comment by zayyeh** [comment]
I'm sorry, could you please clarify? I still can't pass "this" to any method. We were talking about EnemyBase class, not BuildingPanel_Classes...
