### ISSUE TITLE
Issue updating property type

### ISSUE THREAD

**Issue by bgilbert6** [sailro/Reflexil#112]
After updating a property type of a class from int32 to int64, other DLLs referencing the original DLL get this error:

Method not found: 'Int32 Namespace.Class.get_id()'.

Is there any way around this?

**Comment by sailro** [comment]
This is expected when updating the public API surface of a DLL (Perhaps this is not a good idea)

You have to patch referencing DLL as well. This can be a long job, given you have to manually patch all calls to this getter ...
