### ISSUE TITLE
[Suggestion] Include usings from member's class when using "Replace all with code"

### ISSUE THREAD

**Issue by bluuman** [sailro/Reflexil#114]
Currently, when using the "replace all with code" option on a member function, it seems that we have to insert our own usings. I figure it would be more convenient just to grab the usings from the member's class and import them automatically, as those imports are usually necessary to compilation.

**Comment by zayyeh** [comment]
Just a quick tip to speed up a process of inserting your using: Have a program like Punto Switcher and specify autocorrection hotkeys there. For example, "ue [spacebar]" gets replaced by "using UnityEngine;". Will save you some time in a long run.

**Comment by sailro** [comment]
Done, it should be now super easy to copy/paste code from ILSpy decompiler, as imports are now computed with:
- all type references used for members (like parameter type)
- all references used from the current method code
