### ISSUE TITLE
unable to stream assembly to reflector

### ISSUE THREAD

**Issue by omidfz** [sailro/Reflexil#115]
hi
iwanna inject   a empty void method to a .net dll
but saving failed!
and has this error:
unable to stream assembly to reflector  in case of item deletion  make sure you removed all existing referencess.
whats  that  Mean ?
i do not delete anything or anywhere. only try to inject an empty void method
thanx

**Comment by sailro** [comment]
Hi

Could you give us more details ? What is your Reflector version ?

**Comment by omidfz** [comment]
hi
version is  2.1  
and when i try to save the dll with injected mothod  
seeing the error

**Comment by sailro** [comment]
Could you send me this dll ? Perhaps something is already wrong with it. Could you try to peverify it ? (Right click on this assembly, verify).

**Comment by omidfz** [comment]
![2](https://user-images.githubusercontent.com/6241917/33708208-0e5055ce-db4f-11e7-93dc-ab51574f380c.jpg)
hi 
i want to inject this method (Fig 1)to dll
and after inject  give me this error(fig 2)
what can i do to import  the System.IO.File.ReadAllText to solve the problem.?
![1](https://user-images.githubusercontent.com/6241917/33708202-053e8b22-db4f-11e7-8252-53d2b2bfbbd0.jpg)

**Comment by sailro** [comment]
Check assembly references, you probably used the File type from another mscorlib. First make sure you are referencing only one mscorlib, then when selecting File.ReadAllText, make sure that this is from the exact same mscorlib that you use in your assembly reference.
