### ISSUE TITLE
Release for ILSpy 3

### ISSUE THREAD

**Issue by christophwille** [sailro/Reflexil#116]
We are closing in on RTM for ILSpy 3 - would you consider updating your addin for ILSpy 3?

**Comment by sailro** [comment]
Yes sure, I'm just wondering about specific stuff that was added in ILSpy especially for Reflexil, like in this commit:
https://github.com/icsharpcode/ILSpy/commit/10c72948e4010c5ead366ca3869b574be080bf29

**Comment by sailro** [comment]
Ah it seems that this is still present

**Comment by christophwille** [comment]
We moved quite a few cheeses. If you find something (or don't) please let us know.

**Comment by sailro** [comment]
Seems I have a working prototype. I will try to test everything this week.

https://ci.appveyor.com/project/sailro/reflexil/build/artifacts

**Comment by sailro** [comment]
https://github.com/sailro/Reflexil/releases/tag/v2.2
