### ISSUE TITLE
Instruction Reference will missing while use edit on a instruction

### ISSUE THREAD

**Issue by Neutron3529** [sailro/Reflexil#119]
for example
![default](https://user-images.githubusercontent.com/26130174/35404201-1a2f9ae8-023d-11e8-865e-06b4732e6605.png)
while changing instruction "ldc.r4 1" in line 16 to "ldc.r4 2"
![default](https://user-images.githubusercontent.com/26130174/35404394-ca87fde0-023d-11e8-8ab3-3f9b82da8fa0.png)
you can see that, I only change the line 16 but line 11 also changes, which may damage the method.
the version of Reflexil is 2.1, but I do not see any patch for this issue in 2.2
so I create this issue.

**Comment by Neutron3529** [comment]
![default](https://user-images.githubusercontent.com/26130174/35404845-423f26aa-023f-11e8-96d7-d0f1ad193375.png)
![default](https://user-images.githubusercontent.com/26130174/35404855-4b7ef56a-023f-11e8-8709-b4cef78e3842.png
it seems that the newest version(with ILSpy) will also be affected

**Comment by sailro** [comment]
The explanation is that you removed the original instruction, so all other instructions pointing to this one are still refering to the original one.

So two options:
- keep the original, and update it (best)
- patch all references to point to the new instruction

Indeed we should warn the user when try to delete a referenced instruction.
