### ISSUE TITLE
Methods stubs ref/out bugs

### ISSUE THREAD

**Issue by jiangzhen3s** [sailro/Reflexil#12]
hi friend
the  "method stubs"  code  generate algorithm can't gen right ref/out keyword, it is gen  ref all times.

**Comment by sailro** [comment]
Hi.

Yes you are right but is this a problem ? I think this will not prevent Reflexil from fixing calls.
And if we have an out parameter in a method stub, we will have to at least assign it.

**Comment by jiangzhen3s** [comment]
yes.
