### ISSUE TITLE
Add a log

### ISSUE THREAD

**Issue by sup3rgiu** [sailro/Reflexil#121]
Hi,
I'm trying to add a simple log replacing the code with the specific function. This is the code that I'm trying to add:
`Log.Info ("test", "*** A simple log ***");`

But I'm getting:
Error CS0103: The name "Log" does not in exist in the current context.

So i added in the imports: `using Log;`, but now I get:
Error CS0246: The type or namespace name 'Log' could not be found (are you missing a using directive or an assembly reference?).

Probably I'm implementing the log in the wrong way.

Thanks

**Comment by sup3rgiu** [comment]
Still nothing?

**Comment by UlyssesWu** [comment]
Where is `Log` class located? The assembly you're trying to modify is not referring the `Log` assembly probably.

1.  Right Click your assembly -> Reflexil -> `Inject Assembly Reference`
2. Input the `Log` assembly's full name
3. Select the assembly reference you just added, set version and public key token (if have) to be same as `Log` assembly
4. Save assembly. Reload assembly.
5. Now, try updating codes again.

**Comment by sailro** [comment]
@UlyssesWu is right.
