### ISSUE TITLE
Remove strong name update referencing assemblies error

### ISSUE THREAD

**Issue by jrt324** [sailro/Reflexil#122]
When update referencing assemblies:
Error:

Refiexil is unable to save this assembly: File "D:\xxxxx.dll"  being used by another process.The process cannot access the file

**Comment by Neutron3529** [comment]
try to save with another name (such as, d:\xxxxx.patched.dll)
should work.

**Comment by jrt324** [comment]
@Neutron3529   
I have been tired this way ,still not work ,and error  dll is referencing assemblies not current main dll

**Comment by sailro** [comment]
Which host are you using ? ILSpy ?

**Comment by Neutron3529** [comment]
@jrt324 
try another folder or run as administrator
maybe it works because not all folder in the computer is writeable.

**Comment by TranVanLong231** [comment]
Did you find the problem?
I have the same issue

**Comment by Eng-Ahmd** [comment]
I am facing the same problem :(

**Comment by cw2k** [comment]
I can also confirm that bug. (I tested it with **Reflector10**)
... and can add that bug is there since version 2.1.
I loaded 'Reflexil.Reflector.AIO.dll' **version 2.0** and there **removing strong names works**

**Comment by ricklove** [comment]
I also found that the bug exists in ILSpy v3 with Reflexil v2.2. 

I installed ILSpy v2.4 with Reflexil v2.1 and it works fine.
