### ISSUE TITLE
Unable to save change to ILSPy made by Reflexil 

### ISSUE THREAD

**Issue by hellboy81** [sailro/Reflexil#128]
I am trying to modify assembly  (adding one instruction `ret` after operator):

Trying to Update ILSpy object model gotting message dialog:

> Unable to stream assembly to ILSpy. In case of item deletion make sure you removed all existing references  

I am using ILSpy 3.1.0  with Reflexil v2.2

**Comment by sailro** [comment]
Could you give the complete repro of what you are trying to achieve ?

**Comment by sailro** [comment]
Closing as I got no response after 1 month.
