### ISSUE TITLE
reflexil is unable to save this assembly

### ISSUE THREAD

**Issue by huuchungc2** [sailro/Reflexil#129]
Hi,
I can not  save file patch for reflexil 2.2 with reflector version 9.3.0.27 with error. Please let me know how to fix it .thanks

![error](https://user-images.githubusercontent.com/19771084/42360954-034c07a0-8116-11e8-9269-d78afa6cefb9.png)

**Comment by huuchungc2** [comment]
This is file which i need to patch it
[chilkatdotnet4-9.5.0-x64.zip](https://github.com/sailro/Reflexil/files/2169104/chilkatdotnet4-9.5.0-x64.zip)
please help me soon

**Comment by sailro** [comment]
I need more info. You probably made a mistake while patching the assembly.

**Comment by sailro** [comment]
Closing as I got no response after 1 month.
