### ISSUE TITLE
Renaming assembly name causes crash (using ILSpy in Windows)

### ISSUE THREAD

**Issue by Victor-Tseng** [sailro/Reflexil#130]
When I try to rename the assembly name, after input the new name and click OK the ILSpy will crash.

I am using ILSpy 32. with Reflexil 2.2. Below is the log provided by Windows:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	ILSpy.exe
  Problem Signature 02:	3.2.0.3856
  Problem Signature 03:	84cd9b93
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1590.0
  Problem Signature 06:	5787ee1b
  Problem Signature 07:	3e0
  Problem Signature 08:	0
  Problem Signature 09:	System.StackOverflowException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	253c
  Additional Information 2:	253cd6f8d0eeac226b1bda9477044a3d
  Additional Information 3:	29ef
  Additional Information 4:	29ef6445f8f082bde9e55f8f9413f04d

**Comment by sailro** [comment]
I do not reproduce. Perhaps your assembly is protected/broken ?

What about a peverify ?

**Comment by sailro** [comment]
Closing as I got no response after 1 month.
