### ISSUE TITLE
CS1056 & CS1519 errors in "replace all with code" 

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [sailro/Reflexil#137]
thanks for the great tool! make editing fun. but i experience CS1056 & CS1519 errors in "replace all with code" without changes made just by opening from menu see:

![image](https://user-images.githubusercontent.com/46166740/53827768-2aea3f00-3f7c-11e9-84c6-4ff821491335.png)

**Comment by sailro** [comment]
Could you share your assembly + repro steps ?

As a workaround, you can comment all members that you don't plan to use. Reflexil will not try to map them.

**Comment by sailro** [comment]
Closing, as I got no response

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
sailro , Excuse the lack of response on this, i couldn´t provide the assembly files. This errors seemed to be caused from some type of obfuscator that renamed classes names to characters not supported. Sadly i cannot provide assembly, as this binary was not my work.
