### ISSUE TITLE
How can we call or callvirt methods from objects parameterized by generics

### ISSUE THREAD

**Issue by i30817** [sailro/Reflexil#14]
Just the humble List< FOO > is getting me "InvalidProgramException: Invalid IL code" because i can't edit the generics in the callvirt form.

**Comment by sailro** [comment]
We I have to really improve standard dialogs to properly work with generics. it's in my todo list

**Comment by sailro** [comment]
As a temporary workaround, you should try to use "Replace all with code" feature

**Comment by sailro** [comment]
Work in progress:

![image](https://cloud.githubusercontent.com/assets/638167/7231544/37308222-e776-11e4-9b8d-61ed8b2a9543.png)

Result:
![image](https://cloud.githubusercontent.com/assets/638167/7231588/6d2bbbe4-e776-11e4-8011-e5a3cb1297d1.png)

**Comment by sailro** [comment]
This should be done now in the master.
