### ISSUE TITLE
Reflexil is unable to save this assembly: The object of type "System.SByte" cannot be converted to type "System.String"

### ISSUE THREAD

**Issue by 0x6d61726b** [sailro/Reflexil#140]
I opened an executable and tried to save it without modificaton.
When doing so, the following error message showed up (second part was translated from localized messed):

"Reflexil is unable to save this assembly: The object of type "System.SByte" cannot be converted to type "System.String"

Did I do something wrong?

**Comment by sailro** [comment]
Could you share the binary ?

Perhaps it's obfuscated.

Seb

**Comment by sailro** [comment]
Closing old issue without response

**Comment by 0x6d61726b** [comment]
Hello Seb,

sorry for the delay. The binary is obfuscated, but it worked after deobfuscation. 
Thanks for your replay and support.

Best regards
Mark
