### ISSUE TITLE
(Request) Update to use ILSpy 6.0.0

### ISSUE THREAD

**Issue by NickAcPT** [sailro/Reflexil#145]
ILSpy has gotten lots of updates and Reflexil only supports an older version (2.3).

Currently things throw errors:
![error 1](https://i.imgur.com/of0kDGE.png)
![error 2](https://i.imgur.com/xeKHTV5.png)

**Comment by sailro** [comment]
I'm going to have a look. 6.x probably broke some stuff.

REflexil is still working properly with 5.x stable (just tested with 5.0.2.5153)

**Comment by chucklu** [comment]
Encounter the same popup when try to use Reflexil with ILSpy  6.0 preview version.

**Comment by chucklu** [comment]
@sailro  I am using Reflexil.ILSpy.Plugin.dll version 2.3.0(SHA-256: f8f702bc56fc9424f9), It did not work with ILSpy version 5.0.2.5153. And I got a different exception.
I simply put Reflexil.ILSpy.Plugin.dll under the folder of ILSpy.
![image](https://user-images.githubusercontent.com/3004057/76637980-a49d0b80-6586-11ea-9971-1c04cd9ee615.png)

**Comment by chucklu** [comment]
It's my fault that I am using the wrong version of Reflexil. The correct version should be https://github.com/sailro/Reflexil/releases/download/v2.3/reflexil.for.ILSpy.2.3.AIO.bin.zip.
And the file hash is SHA-256: de080bb688d89fa5

**Comment by sailro** [comment]
I updated the repo and published a new release. 2.4 is compatible with ILSpy 6
