### ISSUE TITLE
Difference between release files

### ISSUE THREAD

**Issue by CaledoniaProject** [sailro/Reflexil#147]
Can you explain the difference between these files:

* reflexil.for.ILSpy.2.3.AIO.bin.zip
* reflexil.for.ILSpy.2.3.bin.zip

I'm not sure which one should work with ILSpy 6.X

**Comment by sailro** [comment]
I just published a new release 2.4 compatible with ILSpy 6.

AIO stands for all-in-one: only one il-merged assembly, instead of all dependencies in separate dll.
Feature-wise it's exactly the same.

**Comment by CaledoniaProject** [comment]
@sailro Can you rename Changelog to Changelog.txt in future releases?
