### ISSUE TITLE
Error(s) loading plugin: Reflexil.ILSpy.Plugin : System.TypeLoadException on ICSharpCode.Decompiler.Metadata.Resource

### ISSUE THREAD

**Issue by joujoukinder** [sailro/Reflexil#148]
Hi, 

I am getting the following exception when loadind Reflexil with ILSpy

`Error (s) loading plugin: Reflexil.ILSpy.Plugin
System.TypeLoadException: Could not load type 'ICSharpCode.Decompiler.Metadata.Resource' from assembly 'ICSharpCode.Decompiler, Version = 2.4.0.1963, Culture = neutral, PublicKeyToken = d4bfe873e7598c49'.`

I don't know how to fix it. Car anyone help me please ?

Thanks for your help.

Best regards. 

MS

**Comment by sailro** [comment]
Fixed in 2.5
