### ISSUE TITLE
version 2.4 error

### ISSUE THREAD

**Issue by CodedWithInsulin** [sailro/Reflexil#149]
Kan een of meer van de gevraagde typen niet laden. Haal de LoaderExceptions-eigenschap op voor meer informatie. (ReflectionTypeLoadException)

LoaderExceptions:
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)
Kan bestand of assembly ILSpy, Version=6.0.0.5836, Culture=neutral, PublicKeyToken=d4bfe873e7598c49 of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden. (FileNotFoundException)

**Comment by sailro** [comment]
Fixed in 2.5
