### ISSUE TITLE
ILSpy not loading reflexil

### ISSUE THREAD

**Issue by Guitar-Guy** [sailro/Reflexil#150]
so i downloaded both types... the AIO and the not AIO ... and moved them into the root of ILSpy 6.2.1... the plugin doesnt load... is it the version of ILSpy im using?

**Comment by Guitar-Guy** [comment]
i added them one at a time before deleting and retrying the other Reflexil dll

**Comment by Guitar-Guy** [comment]
![ILSpy](https://user-images.githubusercontent.com/60497181/103323541-3523da00-4a3b-11eb-8d56-3b0f63d57a37.png)
![ILSpy root](https://user-images.githubusercontent.com/60497181/103323542-35bc7080-4a3b-11eb-8108-3a8e80c534dd.png)

**Comment by sailro** [comment]
Did you try with the latest 2.5 ? You need this one for IlSpy 6.2.1

![image](https://user-images.githubusercontent.com/638167/103327037-caa57680-4a07-11eb-9f26-cc04250bb0b6.png)
