### ISSUE TITLE
ILSpy not loading with plugin

### ISSUE THREAD

**Issue by samuelbeepdev** [sailro/Reflexil#151]
<img width="310" alt="Screenshot 2021-02-20 111953" src="https://user-images.githubusercontent.com/25871560/108606209-98602780-736d-11eb-88f7-cf1f7155fe81.png">

Using Reflexil 2.5 AIO and ILSpy 7.0 Preview 2.

**Comment by cosmokid** [comment]
Yes, I get the same issue.

**Comment by sailro** [comment]
Yes it's probably just a matter of recompiling against newer bits (given ILSpy' major version changed).

**Comment by rakion99** [comment]
wait for reflexil to update or use ilspy 6.2.1 instead of the preview versions of ILSpy

**Comment by sailro** [comment]
Fixed with ILSPy 7.1
