### ISSUE TITLE
Cannot add object parameter to callvirt

### ISSUE THREAD

**Issue by MoritzioM** [sailro/Reflexil#16]
Please see 
![getcomponent-type2](https://cloud.githubusercontent.com/assets/11395542/6810573/00d11c12-d238-11e4-8800-7662682eede5.png)

I want to use the code line highlighted in blue in a different method but cannot replicate the TorchCharacterController parameter:
!!0
![getcomponent-type2a](https://cloud.githubusercontent.com/assets/11395542/6810623/75dd944a-d238-11e4-8f3b-05dc0361d080.png)

When I select the UnityEngine.Component.GetComponent method, I do not see a way to identify TorchCharacterController as the parameter. How should I do that?

**Comment by sailro** [comment]
see https://github.com/sailro/Reflexil/issues/14
I have to improve all generic related stuff

**Comment by sailro** [comment]
Work in progress (about generic issue):

![image](https://cloud.githubusercontent.com/assets/638167/7231544/37308222-e776-11e4-9b8d-61ed8b2a9543.png)

Result:
![image](https://cloud.githubusercontent.com/assets/638167/7231588/6d2bbbe4-e776-11e4-8011-e5a3cb1297d1.png)
