### ISSUE TITLE
I Can't Save modified assembly ...

### ISSUE THREAD

**Issue by moriybala** [sailro/Reflexil#17]
When I done my modification and eve not modify assembly and go to save that , reflector show this message:
"Reflexil is unable to save this assembly: Unable to cast object of type 'System.Int32' to type 'System.String'."
help me to solve this.
![capture](https://cloud.githubusercontent.com/assets/11704464/6884896/c4357108-d61b-11e4-975f-f4023848cdef.PNG)

**Comment by moriybala** [comment]
@sailro 
any body here !!!!!!
help me ...

**Comment by sailro** [comment]
Can you provide more details ? If you just save the assembly without modifying it, does it work ?
If yes, you have just broken something with a bad assembly alteration. What are you trying to do ?

**Comment by moriybala** [comment]
Hi 
Yes when i just save the assembly without modifying it, it doesn't work.
For more details : this app protect with smart assembly, and i was clean that with latest ver of de4dot.
App run good ,scan &check it and not protected andno strong name ...
But when use reflector with any chenge this,can't save ,in fact" unable to save ..."
And i install & re install visual studio 2010 .
Finally , i have to bit patch assembly.
Thanks for your attention ...

**Comment by btlramesh** [comment]
how to fix it?

**Comment by moriybala** [comment]
I can't to fix it , but by byte patch method bypass app.....

**Comment by huuchungc2** [comment]
Pls let me know how to fix it
