### ISSUE TITLE
build failed to build Reflexil for ILSpy AIO

### ISSUE THREAD

**Issue by noliar** [sailro/Reflexil#19]
It's caused by the missing outname for ILMerge.exe.(ILMerging into ~9...Must specify an output file!)
The reason is that "set ILMERGEOUTPUT=%ILMERGEINPUT%" will be effective  when if-else statement ends.
So we can add "setlocal EnableDelayedExpansion" to enable the delayed expansion and change "set ILMERGEOUTPUT=%ILMERGEINPUT%" to "set ILMERGEOUTPUT=!ILMERGEINPUT!" or just change it to set ILMERGEOUTPUT=.\output\Reflexil.%PLUGIN%.Plugin.dll

**Comment by sailro** [comment]
Fixed thanks.
