### ISSUE TITLE
ILSpy support

### ISSUE THREAD

**Issue by KOLANICH** [sailro/Reflexil#2]
Would you add [ILSpy](https://github.com/icsharpcode/ILSpy) support?

**Comment by oldmud0** [comment]
Hey, would you mind if you uploaded the build on a less volatile host? I'm interested in this endeavor, but the download links seem to be dead. Thanks!

**Comment by sailro** [comment]
https://www.dropbox.com/s/jdu8h32whqo6h30/reflexil.for.ILSpy.2.0-preview3.zip

**Comment by XODE0** [comment]
hello
i waited all time to see reflexil in ILSpy 
thanks 
however,there's a problem when start ILSpy
![capture](https://cloud.githubusercontent.com/assets/10565186/5781897/a51abb68-9db6-11e4-8775-9c83d8c0bd13.PNG)

**Comment by sailro** [comment]
Did you use the preview file attached to this thread ?

Because you cannot compile yet yourself the plugin and use it with an official ILSpy release.
I need some upgrades, i made a PR for that:
https://github.com/icsharpcode/ILSpy/pull/523
But no response so far from ILSpy team.

(You can also build ILSpy from my fork https://github.com/sailro/ILSpy)

**Comment by XODE0** [comment]
yes i used the one attached in previous comment
(this one https://www.dropbox.com/s/jdu8h32whqo6h30/reflexil.for.ILSpy.2.0-preview3.zip)
,i will try to build ILSpy from your fork .
even ILSpy forum is dead i don't know what happens but i wish they could continue there development for both ILSpy and SharpDevelop .
 thank you.

**Comment by GeorgeHahn** [comment]
I ran into an issue with IL editing today. I edited a LDSTR instruction in a function that returned a generic `List`. The saved binary threw an exception for ``Could not load type 'System.Collections.Generic.List`1' from assembly``. It looks like the generic `<...>` part of the `List` was dropped.

The binary in question was `JBSCore.dll` from [John's Background Switcher](http://johnsad.ventures/software/backgroundswitcher/windows/). The function was `Pixabay.GetPhotos`. Let me know if you need any other info.

**Comment by sailro** [comment]
I will check that. Thanks

**Comment by raplin** [comment]
It's cool but... dumb question; how do I save the modified executable? :-)

**Comment by sailro** [comment]
Yes related to https://github.com/sailro/Reflexil/issues/14

**Comment by lwlin** [comment]
https://github.com/icsharpcode/ILSpy/releases/tag/2.3
ILSpy has relased 2.3 and i find this Improved extensibility for Reflexil ,may be you can update the plugin .Also i got puzzle that the window of Reflexil will take place of the window of analyzer ,i think it is inconvenience

**Comment by GeorgeHahn** [comment]
Ah, sorry I missed your previous reply. Yes, Reflexil + ILSpy is a wonderful combo. Really enjoying it!

**Comment by sailro** [comment]
Work in progress (about generic issue):

![image](https://cloud.githubusercontent.com/assets/638167/7231544/37308222-e776-11e4-9b8d-61ed8b2a9543.png)

Result:
![image](https://cloud.githubusercontent.com/assets/638167/7231588/6d2bbbe4-e776-11e4-8011-e5a3cb1297d1.png)

**Comment by egorchik007** [comment]
Hi! I've downloaded the latest release of both reflexil and ILSpy, but how do I use them together?
I've noticed that ILSpy contains the same DLLs that are shipped with reflexil build, but I don't have clue how to make it work as on your video. Thanks!

**Comment by sailro** [comment]
The demo build available in this thread was made with a custom ILSpy version.
Now that latest ILSpy release contains everything Reflexil need to work (i made several PR for that and they were accepted in the ILSpy repository), you should take the Reflexil/ILSpy demo build and overwrite everything using the official ILSpy release.

When Reflexil 2.0 will be released, only the necessary Reflexil dll will be shipped.

**Comment by nitescua** [comment]
I am a bit confused. 
The latest released version of Reflexil (v1.9) does not work with ILSpy, correct?
Only the preview version you attached in this thread does?

**Comment by sailro** [comment]
Yes you are right. You can also use the master to compile a working version.

I have some extended tests to perform and finalizing some work on generics/GUI then i will release a v2 with everything.

**Comment by nitescua** [comment]
thank you.
oh, and your work is amazing :)

**Comment by oldmud0** [comment]
Yay! Mission success!
