### ISSUE TITLE
Reflexil can't find sn.exe

### ISSUE THREAD

**Issue by aguythere** [sailro/Reflexil#20]
Reflexil insists that sn.exe is not installed even though I have several windows SDKs installed most of which include some incarnation of the sn.exe file.

I have tried every possible version I could think of for sn.exe's file path (C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\sn.exe) but nothing seems to work and Reflexil continually refuses to acknowledge sn.exe's existence.

I've set both the 'PATH' user variable (which is currently set to "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A") and the 'Path' system variable (currently set to "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A").

What am I doing wrong? What needs to be changed?

**Comment by aguythere** [comment]
I guess I can't delete but I fixed it by moving the sn.exe file and snrc.dll files to the .net reflector folder. However verification skipping always fails.

**Comment by sailro** [comment]
When using the PATH environment variable, sn filename must be directly included (which is different than the SDK directory).
