### ISSUE TITLE
How to use "Multiple instructions references"

### ISSUE THREAD

**Issue by btlramesh** [sailro/Reflexil#21]
Hi,
  how can i use "Multiple instructions references" in operand type and which option should i select in Op Code

![screen](https://cloud.githubusercontent.com/assets/10597536/7108882/1cef3078-e1b0-11e4-8e26-31f256d1fe79.jpg)

![screen3](https://cloud.githubusercontent.com/assets/10597536/7108883/1cf46bc4-e1b0-11e4-918a-3a60a7ae5a75.jpg)

![screen2](https://cloud.githubusercontent.com/assets/10597536/7108884/22a10564-e1b0-11e4-86b3-7c19aa5580c5.jpg)

**Comment by sailro** [comment]
Multiple instruction references is only valid with the switch IL opcode, because it implements a jump table.

https://msdn.microsoft.com/fr-fr/library/system.reflection.emit.opcodes.switch%28v=vs.110%29.aspx
