### ISSUE TITLE
Unable to save assembly 

### ISSUE THREAD

**Issue by shanewilhelm** [sailro/Reflexil#23]
When opening and trying to save an unmodified exe, I encounter this error. Any suggestions?

![error](https://cloud.githubusercontent.com/assets/9032171/7602513/5ad98514-f8da-11e4-87d0-c47e420c73bb.png)

**Comment by sailro** [comment]
Yes this is due to assembly resolving. Fixed in the master and will be available in 2.0.
We will only have to add the assembly in the Reflector assembly list.
