### ISSUE TITLE
Calling an internal constructor

### ISSUE THREAD

**Issue by PELock** [sailro/Reflexil#24]
Hi, I have a code that is calling an internal constructor of the class

class MyClass: IClassInterface
{
 internal MyClass(string param1);
...

it's called from another method

MyClass myClass = new MyClass("abc");

when I try to replace the code in Reflexil (replace all code with C#) I get an error CS1729

I think it shouldn't be an issue for Reflexil unless it's MS fault :)

**Comment by sailro** [comment]
When using "Replace All With Code" feature, we create a new assembly referencing the original one.
So you have to call members with a good scope. The best thing to do is to first change the constructor scope to public, save and reload the assembly then use "Replace All..." feature.

**Comment by PELock** [comment]
Well, this couldn't be done and it was mixed mode assembly so the Mono.Cecil failed anyway at saving modified assembly ;)
