### ISSUE TITLE
suggestion: add a CI service

### ISSUE THREAD

**Issue by noliar** [sailro/Reflexil#28]
Using a CI service like [AppVeyor][appveyor] (Free for open-source projects), we can get the latest PR build without downloading the source code.
eg: [sephz/reflexil][build]. And it's configure is [appveyor.yml][config]

[appveyor]: http://www.appveyor.com/
[config]: https://github.com/noliar/Reflexil/blob/master/appveyor.yml
[build]: https://ci.appveyor.com/project/sephz/reflexil

**Comment by sailro** [comment]
Yes I was already thinking of that.
Will check that soon.

**Comment by sailro** [comment]
Done

**Comment by noliar** [comment]
@sailro :smile: But I think the link (in README.md) of nightly release should be "https://ci.appveyor.com/project/sailro/reflexil/build/artifacts", which makes us obvious to know where to download.

**Comment by sailro** [comment]
Yes you are right
