### ISSUE TITLE
suggestion:add the "replace" feature

### ISSUE THREAD

**Issue by yeaicc** [sailro/Reflexil#29]
Replace:
Can help us to use another method to replace the target method.

**Comment by sailro** [comment]
Well we have to be in the same exact context to do that: same parameters type, same return type, same 'state' (static vs instance etc.)

Can you describe a bit more your use case ?

**Comment by yeaicc** [comment]
Sorry my English is very pool....
For example:
I perform replication on a method in an Assembly, and then paste the target method to be performed on the target Assembly.
