### ISSUE TITLE
Feature suggestion: "Replace all with code" should default to existing code

### ISSUE THREAD

**Issue by BlueRaja** [sailro/Reflexil#31]
Rather than `default(type)`.

I realize copying doesn't take much time, but it's a pain when editing a lot of methods.  Also, it's good UX in general, following the old adage **"Make the common case the default"**

**Comment by sailro** [comment]
Reflexil is not a decompiler, and if we do that we will often have non compilable code because of the special injection context (nested types/scopes/assemblies).

You can still use the decompiler view of your favorite host (Reflector/ILSpy/JustDecompile)
