### ISSUE TITLE
Can't edit Unity assembly - CompilerVersion = "v4.0" required

### ISSUE THREAD

**Issue by beatcracker** [sailro/Reflexil#34]
I'm trying to edit particular method in Unity's `Assembly-CSharp.dll` using Reflexil 2.0 and `Replace all with code` functionality . This method uses optional parameters, so it can't be compiled using `Unity\Silverlight` profile or `.NET 4.0` (no `/nostd` switch) and I'm getting

* `Compiler Error CS0241: Default parameter specifiers are not permitted`.

To get past this I've modified `Compiler.cs`:

from

```csharp
public static readonly CompilerProfile UnitySilverLightProfile = new CompilerProfile {
    Caption = "Unity/SilverLight",
    CompilerVersion = "v3.5",
    NoStdLib = true};
```

to

```csharp
public static readonly CompilerProfile UnitySilverLightProfile = new CompilerProfile {
    Caption = "Unity/SilverLight",
    CompilerVersion = "v4.0",
    NoStdLib = true};
```

and tried again, but this time the code wouldn't compile because of missing stubs for two enums:

* `CS0246	The type or namespace name 'Button' could not be found (are you missing a using directive or an assembly reference?)`
* `CS0246	The type or namespace name 'Axis' could not be found (are you missing a using directive or an assembly reference?)`

If I add stubs manually, the code will compile, but saved assembly will reference those two manually added stubs from Reflexil's temporary generated intermediate assembly:

![Assembly reference](https://cloud.githubusercontent.com/assets/7583050/9185703/c3e3a0ac-3fc6-11e5-86ea-fa32ce41b4e1.png)

Is there any workaround for this?

**Comment by sailro** [comment]
Interesting, can you give me this Assembly ?
So I can better understand the exact issue.

**Comment by beatcracker** [comment]
Here is [link to archive](https://www.dropbox.com/s/r9rokb143iz7qa6/Managed.zip?dl=0) with `Assembly-CSharp.dll` and referenced assemblies. I'm trying to edit `GetButton` method in `SmartInput.XboxControllerInput`.

I need to modify this part of the method:
```csharp
case Button.Select:
    return MoonInput.GetButton(m_joystickButton6Map[index]);
```
So it becomes this:
```csharp
case Button.Select:
    return (controller.IsBackPressed || MoonInput.GetButton(m_joystickButton6Map[index]));
```
Missings stub are:
* `SmartInput.XboxControllerInput+Axis`
* `SmartInput.XboxControllerInput+Button`

_P.S._ Actually, I've first tried to do it directly via `CloneMethodBody` method (I'm using [stripped down version of Reflexil](https://github.com/beatcracker/GUILess-Reflexil) from PowerShell) and thought that it was something wrong with my code. But then I've tried to do it via Reflexil's GUI and hit the same issue. As far as I understand from Reflexil's code, it's supposed to fix references for stubs, so they point to original assembly, but it looks like this doesn't happen.

**Comment by sailro** [comment]
Ok, now mapping issues should be fixed with https://github.com/sailro/Reflexil/commit/407dc7c9bd41a9b3286804a324618cb5434324da and
https://github.com/sailro/Reflexil/commit/01a02e2eadf2af521adb0cadc428f771c088ce33

Can you try with the latest build please and give me some feedback ?
https://ci.appveyor.com/project/sailro/reflexil/build/artifacts

Thanks

**Comment by sailro** [comment]
I was able to alter your demo assembly following your repro steps.

Everything is fine, without any ghost reference (btw it should be now impossible to craft such an invalid reference).

Closing.
