### ISSUE TITLE
Cannot edit Silverlight 5 Assemblies

### ISSUE THREAD

**Issue by Markus1980Wien** [sailro/Reflexil#35]
Problem is located in Mono.Cecil\BaseAssemblyResolver.cs

in function AssemblyDefinition GetCorlib (AssemblyNameReference reference, ReaderParameters parameters)

which cannot not handle corlib.dll Version 5.0.5.0 which is used for Silverlight 5

**Comment by sailro** [comment]
Which version are you using ?

Starting with v2.0, if you load the proper mscorlib in the host (Reflector, IlSpy) , Reflexil will lookup the assembly in the assembly list first.

**Comment by sailro** [comment]
Re-tested this one.

Everything works if you add mscorlib/system.dll from C:\Program Files\Microsoft Silverlight\5.x.x.x.

Reflexil will use loaded assemblies for resolution and Mono.Cecil GetCorLib will not fail.

**Comment by sailro** [comment]
+added Silverlight 5 profile in 61067dcb795c3570b211a02fa0b6c7088b69dbf0
