### ISSUE TITLE
"No match for type *** in source assembly" in Reflexil 2.0

### ISSUE THREAD

**Issue by UlyssesWu** [sailro/Reflexil#37]
In a situation like this:
	
	class Father
	{
		class <son>_c__Iterator2 //A nested compiler generated type
		{
			internal int $PC;
			public bool MoveNext();
			...
		}
	}

In order to replace code in `MoveNext()`, at first I have to rename `$PC` , `<son>_c__Iterator2` etc. After rename (of course I have saved & closed & reloaded the assembly):

	class Father
	{
		class child
		{
			internal int childPC;
			public bool MoveNext();
			...
		}
	}

And I try to use "Replace all with code" on `MoveNext()`, and compilation is successful. But when I click "Ok", a error occured : **No match for type child in source assembly**.

I realized it must be something wrong with Reflexil 2.0, because I can do the same thing with no error by switching to Reflexil 1.9.

--EDIT--

It's wired. When replacing code, if you don't touch any variables in class `child`, there will be no error. Otherwise you will get that error (only in Reflexil 2.0) .
Like this:

	//Will pass
	public bool MoveNext()
	{ return true; }

	//Will fail
	public bool MoveNext()
	{
		this.childPC = 1;
		return true; 
	}

**Comment by BlueRaja** [comment]
This seems to be the same issue I brought up in #30.  I am still seeing the issue too, inner classes are not detected properly.

**Comment by sailro** [comment]
Fixed for me in 41720459c40447ff90f5272d1ace2f6fdd7e568b

**Comment by StoneMoe** [comment]
I'm experiencing this issue at Reflexil 2.1(the lastest version from offical site when i post this)

When using "Replace all with code" feature, I copy all the code decompiled by reflector or ILSpy, and fix the missing import and references, than compile with no error in code window.

But when click on OK to write instructions to the assembly, It shows "No match for type c__DisplayClass2 in source assembly".

So I looked into the original instructions and the compiled instructions by Reflexil
Original: newobj xxxxxxxx/<>c__DisplayClass3b::.ctor()
Reflexil compiled: newobj xxxxxxxx/<>c__DisplayClass2::.ctor()

And the compiler generated nested class which named with c__DisplayClass2 even not existed.

**Comment by StoneMoe** [comment]
OK...sorry for the distrubing, I notice there is a tip say "can't reference ancestors class", it is indeed a issue about this.

But can i edit the instructions in the code compile window? The edit option is grey out there, maybe it's a missing feature?
