### ISSUE TITLE
Create new variable of generic scope

### ISSUE THREAD

**Issue by npetrovski** [sailro/Reflexil#41]
Hi, I might be wrong of the way I am trying to add new variable of type uint, but it also could be a bug or misconfiguration.

At the "Variables" tab I select "Create new..", I put a Name of my new variable and select Type Scope -> Generic parameter. The problem is that the 3th field "Type" is mandatory, but I cannot select anything from it since it is empty.

Is this problem connected to the fact that the method does not have any other variables defined, or I misunderstood the way a new variable could be added with Reflexil?

--Nick

**Comment by npetrovski** [comment]
My bad - I should be adding a Reference to mscorlib / System.Int32 instead and not a Generic parameter. Thanks.

**Comment by sailro** [comment]
Yes 'Generic' is to be understood as Generic type support :p
