### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by npetrovski** [sailro/Reflexil#42]
Nice to have @ Instructions Tab:

1.  It would be very nice to have a column "Bytes" - hex representation of the OpCodes (quite nice for learning and debugging purposes)
2. An option for "Binary Edit" selected instructions - allowing to put directly HEX bytes instead of editing instruction-by-instruction. Really nice when you want to faster update and debug.
3. An option to "NOP" selected instructions, not just DELETE (replace selected instructions with NOPs)

**Comment by sailro** [comment]
I will add #1 and #3 quickly.

#2, I have to think about it.

Seb

**Comment by saggycondom** [comment]
1. search bar for instructions
2. code injection

**Comment by sailro** [comment]
Continuing in #51
