### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Splamy** [sailro/Reflexil#43]
The type selector of Reflexil always felt like the most clumsy part of the interface for me. Searching for a simple Int32 or float from System, or filtering for a class name often takes me way too long.
In my own project i have a binay way to search: either type the type or select it from the tree, so this way looking for an int is simply int[enter].
Here is a screenshot so you can see what I'm trying to explain: ![Image of TypePicker](http://puu.sh/l6GcZ/1067b6b70a.png)
(the lower box is the found TypeReference from the field above)
My implementation of this is very small and compact but also somewhat limited, yet for now it was always enough.([link](https://github.com/Splamy/ILPatcher/blob/testbranch/ILPatcher/Interface/CreateTypeForm.cs#L69))

So. Could Reflexil use something like that or would it only be unnecessary overhead?

**Comment by sailro** [comment]
Yes, I am also thinking of something simpler. But it can be more complex than that, as a type can be found in several distinct assemblies (like different assembly versions)

**Comment by sailro** [comment]
Closing, what we have is far from being perfect, but it's mandatory to perfectly know the working assembly in case we have several instances of the same assembly with different versions loaded in the host
