### ISSUE TITLE
AIO?

### ISSUE THREAD

**Issue by alexreg** [sailro/Reflexil#46]
What does "AIO" mean for the releases? I think this deserves an explanation.

**Comment by UlyssesWu** [comment]
I guess it means All In One.
Refiexil uses many dll files, and the AIO version is the one which all .dll files are merged into one .AIO.dll file.

**Comment by alexreg** [comment]
Aha, that might well be the case yes! Thanks.

**Comment by sailro** [comment]
Exactly, AIO is an ilmerged version of all assemblies.
