### ISSUE TITLE
Unable to stream assembly to ILSpy

### ISSUE THREAD

**Issue by ankilla** [sailro/Reflexil#48]
1) When trying to inject field to (Assembly-CSharp.dll)I am getting error as
"Unable to stream assembly to ILSpy. In case of item deletion make sure you removed all existing references"
2) When trying to save getting error as:
"Reflexil unable to save. Failed to resolve UnityEngine.Rendering.CameraEvent"
But at the same time its working with other files. I am facing the problem with this particular dll.

Attached for reference (as dll is not supported I renamed .dll to .txt)
[Assembly-CSharp.txt](https://github.com/sailro/Reflexil/files/34572/Assembly-CSharp.txt)

**Comment by sailro** [comment]
Did you try to add UnityEngine assembly in the host assembly list (Reflector/IlSpy) ?
Reflexil will try to use them for lookup.

**Comment by ankilla** [comment]
Yes Its happening only to this assembly

**Comment by sailro** [comment]
If you load UnityEngine.dll from Program Files\Unity\Editor\Managed, into Reflector/ILSpy, this is working fine.

**Comment by JusticeWithWellMaintainedSixPackAbs** [comment]
thanks man i tried putting the unityengine it works :) tyvm i had this problem for so long @sailro
