### ISSUE TITLE
Feature request: Add HEX column in "Method Definition" - "Instructions" grid

### ISSUE THREAD

**Issue by LinoBarreca** [sailro/Reflexil#51]
Hi there.
It would be very, very useful if the Instruction window had an "HEX" column too.
Actually ILDASM has an option to put the hexadecimal into the .IL files and it's really useful (actually I have to use them both together to do what I need).
Why would that be useful in a real world scenario?
If you have the hexadecimal you could just find the hexadecimal in the original file and byte patch it with an hex editor.

Example:
Original assembly:
```
.method public hidebysig instance bool  IsLicenseValid() cil managed
// SIG: 20 00 02
{
  // Method begins at RVA 0x2e2d4
  // Code size       337 (0x151)
[...]
  IL_0000:  /* 00   |                  */ nop
  IL_0001:  /* 02   |                  */ ldarg.0
  IL_0002:  /* 7B   | (04)00028B       */ ldfld      string thisclass::serialNumber
  IL_0007:  /* 28   | (0A)000033       */ call       bool [mscorlib]System.String::IsNullOrEmpty(string)
  IL_000c:  /* 0D   |                  */ stloc.3
  IL_000d:  /* 09   |                  */ ldloc.3
  IL_000e:  /* 2C   | 11               */ brfalse.s  IL_0021
```
...we want to skip this check and jump anyway to another instruction...
basically at IL_0001 we want to add a BR (and insert a NOP after to keep hex alignment).

With ILDASM I have the exact position in which I have to search for the method and the hex to patch.
I can write the new instruction with the "edit function" and I would obtain something like:
```
  IL_0000:  /* 00   |                  */ nop
  IL_0001:  /* 38   | 38010000         */ br         IL_013e
  IL_0006:  /* 00   |                  */ nop
  IL_0007:  /* 28   | (0A)000033       */ call       bool [mscorlib]System.String::IsNullOrEmpty(string)
```

Now that I have the original and patched hexadecimal values I can just hex replace 
"02 7B 8B 02 00 04" with
"38 38 01 00 00 00" without using the "save" feature of reflexil (it mangles the assembly too much)

At the moment, without the "hex" column, I have to edit with reflexil, save the patched with reflexil, ildasm original and patched (with hex) and do substitutions.

**Comment by sailro** [comment]
I understand the use case, but Reflexil is more high level. When saving an assembly, Mono.Cecil will re-compute everything before writing, so we cannot know in advance the exact dump of the method body or the exact offset where the body will be. The only thing we can display is the opcode value.
