### ISSUE TITLE
Edit property in ILSpy

### ISSUE THREAD

**Issue by Ravenheart** [sailro/Reflexil#53]
Greetings, how can one edit a property with ILSpy? I looked around everywhere and can't find an option to do it.

**Comment by sailro** [comment]
I had to inspect the ILSpy sourcecode, to remember how to do...

Just select C# - no transform as language. It will properly display accessor nodes under property nodes.

![image](https://cloud.githubusercontent.com/assets/638167/12205713/2433dfe4-b5f1-11e5-9f83-43ae5a4cf26b.png)

With standard C# language, accessors are hidden.

![image](https://cloud.githubusercontent.com/assets/638167/12205743/5d61ee82-b5f1-11e5-95bd-a7754c86de16.png)

cc @dgrunwald

Seb

**Comment by Ravenheart** [comment]
Unfortunately that option is only available in debug builds of ILSpy. Is there a work around for production builds?

**Comment by sailro** [comment]
If you switch to IL language, it will do the same. Not very convenient I agree....

**Comment by chucklu** [comment]
@sailro  Thanks for the information here, I got the Debug version of ILSpy https://ci.appveyor.com/project/icsharpcode/ilspy/builds/26612291 and it works with Reflexil.
