### ISSUE TITLE
Unable to save assembly

### ISSUE THREAD

**Issue by thriada** [sailro/Reflexil#56]
Hi everybody.
This issue was already discussed here: https://github.com/sailro/Reflexil/issues/23
But the problem is not solved. I use Reflexil v.2.0 + ILSpy and receive an error message about assembly resolving. In Telerik JustDecompile + Reflexil 1.8 is just the same problem with the same assembly present.
Screenshot: http://s22.postimg.org/4kxqp1am7/Untitled_1.png

**Comment by sailro** [comment]
This one is fixed is the master and will be available with next release (or you can downloads artifacts from CI builds).

Regarding JustDecompile, I am currently integrating the direct support in the Reflexil repo. So you will be able to use an updated version shortly.

**Comment by sailro** [comment]
Yes, you should just add this assembly to the ILSpy assembly list so that Reflexil can resolve it...

**Comment by thriada** [comment]
I tried it of course, added all possible assemblies already, but can not find out which assembly is necessary. Could you please make Reflexil's error messages about assemblies more informative?
