### ISSUE TITLE
CS1703 - mscorlib referenced twice 

### ISSUE THREAD

**Issue by GAFO** [sailro/Reflexil#58]
Hello,
Im currently reversing/bughunting and in case of software with mscorelib I run into
big trouble.

As soon as I 

- Nagivate to a function e.g. foo()
- Copy all code
- RightClick on Instructions  (in reflexil)
- hit "Replace all with code..."
- paste the orginal code
- compile for testing 
-result: error as named

I did clearly not reference anything twice, i just dragged the .dll for analysing into 
JustDecompile, enabled Reflexil  and did the mentioned things above.
I dont know why this happens, but it makes me unable to make testings.

,greetings  

ps: version 1.8 (only one available for JustDecompile)  && compiling in net 4 (but tried 2.0, 3.5 also)

 -> In my opinion it would be better to be able to write directly into the code, save and reload >.<

**Comment by sailro** [comment]
Yes, this is fixed in 2.0.

It was related to a bug in mapping types after importing.
I am also working on integrating JustDecompile directly in this repo (see justdecompile branch)

Thanks

**Comment by GAFO** [comment]
Oh great :+1:   
One slight suggestion of me:
once you hit "Replace all with code..."  may add the existing one already, it would be
very usefull instead of c/p the old one and add adjustments :) (or a messagebox which asks
"do you want to keep the existing code of function xy" )

Oh and one last report: (since i dont know if its fixed)
I had to struggle with injecting functions too, after creating one I added to an existing function
a call to that injected one and it threw some erros 

e.g. (pseudo)

call existing_func1
call existing_func2
call existing_func3
ret

to 
call existing_func1
call existing_func2
call existing_func3
call InjectedFunc
ret

but as soon as the 2.0 patch arrives here, I will do it through the real code, not through 
instructions :)
