### ISSUE TITLE
Cannot select operator methods when creating/editing call/callvirt operations.

### ISSUE THREAD

**Issue by HoneyFox** [sailro/Reflexil#59]

**Comment by HoneyFox** [comment]
Looks like (maybe part of) the reason is that at MemberReferenceForm.cs:732, the visitor filters out these methods with "isSpecialName" == true.

**Comment by sailro** [comment]
Yes, this is exactly why. This was done because property getter/setter and event add/remove are handled elsewhere, but we do not have to filter operator methods
