### ISSUE TITLE
Feature request: Rename all instances

### ISSUE THREAD

**Issue by NiKiZe** [sailro/Reflexil#61]
Hmm thinking about it, what I really would want is some way to script Reflexil to do a lot of renaming/cleanup work, but here goes my initial thoughts anyway...

If there is a field, property or function of/returning type ```b``` and have name ```a```, and that exists in multiple places, it would be great to be able to rename all of them in one go.

Maybe could be done by extending the rename dialog with "rename all instances of this type", it should also be possible to filter to only rename if the original name is same as for the current rename.

Also being able to only rename if it does not generate a duplicate name.

Additional variant would be to rename and keep original name as part of new name, something like new name: "newName_${oldname}"

Different feature but similar in nature: Be able to remove all attribute occurrences in an assembly, with possibility to select exact or wildcard matching for any attribute arguments.

**Comment by sailro** [comment]
This should be already the case. Because we use the Cecil object model, so everything should be updated.

**Comment by NiKiZe** [comment]
You are referring to one object being renamed?

While what I'm looking for is a way to rename multiple objects in the same manner...

```C#
public class A {
    public obType a;
}
public class B {
    public obType a;
}
public class C {
    public otherType a;
}
```

Concider i would like to rename all fields of type obType, to do so now you need to go thru all occurances one by one to rename them, but it would be great to have a way to rename them all in one go (as long as the destination field name is not taken by something else) also in this specific case I would like to be able to set it to only rename if the existing name matches ^[a-z]{1,2}$

And the other variant is to rename all fields of name "a" to include the type, so they become a_obType and a_otherType.
