### ISSUE TITLE
Extraneous bits in Flags

### ISSUE THREAD

**Issue by peter-volkov** [sailro/Reflexil#62]
Hi @sailro !

Windows 10 x64
Reflector 8.5.0.179 
Up to date Reflexil 2.0

I'm opening x86 version of mscorlib.dll in Reflector, then I start Reflexil verify procedure on this assembly, and it return errors (see screenshot https://yadi.sk/i/8R5zLIJsqWhMt )
If i'm trying to save this assembly and start any .NET app using this .NET4.0 mscorelib - the app fails with 
"Process is terminated due to StackOverflowException."
When I do the same procedure with any other assembly, including GAC assemblies like System.Net.Http.dll - everything runs perfectly.

What is the problem with the mscorelib? Why Reflexil verification fails without any changes made?

Thank you so much for your great product and your kind support.

UPD1 ilspy + reflexil: the same result, errors "Extraneous bits in Flags"
UPD2 ildasm+ilasm sucessfully reassembled mscorelib, and this reassembled mscorelib seems to work well - I see no crashes

**Comment by sailro** [comment]
Hello Peter,

Perhaps a bug in Mono.Cecil, that we use to read/write assemblies.
The PEVerify wrapper that we use, try to save the assembly as a temporary file before verification, even if no changes are made.

I will check for possible fixes in the main Mono.Cecil branch.

Thanks

**Comment by sailro** [comment]
Fixed with Mono.Cecil 0.10 upgrade
