### ISSUE TITLE
No ability to modify code for property setter/getter

### ISSUE THREAD

**Issue by scottbilas** [sailro/Reflexil#65]
The method editing is awesome! Could it be wired up to the property setter/getter methods as well?

**Comment by sailro** [comment]
This is already possible, just go to the getter/setter method under the property. If you are using ILSpy, you have to change the "language" from C# to IL. By default ILSpy will hide getters/setters

**Comment by scottbilas** [comment]
Good guess - I was using ILSpy. Thanks!
