### ISSUE TITLE
Missing feature(Mabie?)

### ISSUE THREAD

**Issue by ElementalVenom** [sailro/Reflexil#67]
Hello so I'm not sure if this is a missing feature with reflexil or if I'm just doing it wrong. But I'm trying to modify a assembly compiled by unity and replicate the addComponent method. When looking at the IL instruction it looks like [THIS](http://s33.postimg.org/bz2qbnvin/ILQuestion.png)

As you can see it says !!0 in front and I don't know what that means?
Any help would be appreciated.

**Comment by sailro** [comment]
!0 is a placeholder for a generic parameter. Properly manipulating generic methods or types is now supported in Reflexil, but requires knowledge. You should try on a demo assembly to understand how it works.
