### ISSUE TITLE
Adding Interfaces to UnityEngine.dll results in "Unable to find ___" for many methods

### ISSUE THREAD

**Issue by M-Pixel** [sailro/Reflexil#68]
For example,

```
Unable to find method SendReapplyDrivenProperties in [UnityEngine.dll]UnityEngine.RectTransform
 
(Filename: C:/buildslave/unity/build/Runtime/Scripting/CommonScriptingClasses.cpp Line: 28)

Unable to find method SetMouseMoved in [UnityEngine.dll]UnityEngine.SendMouseEvents
 
(Filename: C:/buildslave/unity/build/Runtime/Scripting/CommonScriptingClasses.cpp Line: 28)
```

This happens upon launching Unity after adding an assembly reference, and modifying a class to reference an Interface in the added assembly.

The same thing happens whether using IL Spy or .NET Reflector.

**Comment by sailro** [comment]
Hard to say without exact repro steps, but you should use the "Verify" feature to check that you are doing something valid. Perhaps you missed something during the assembly alteration.

**Comment by theqwertman** [comment]
Verification fails even on the unmodified source DLL, so it seems like it's obfuscated or incompatible somehow. I guess this means there's no hope trying to modify the DLL?

**Comment by sailro** [comment]
Did you try the deobfuscate tool that comes with Reflexil ? (right-click on assembly, search for obfuscators)

**Comment by M-Pixel** [comment]
That results in "No Obfuscator Found (or unknown)"

**Comment by sailro** [comment]
Seems that the file is obfuscated with an unknown obfuscator
