### ISSUE TITLE
throw NullReferenceException sometimes

### ISSUE THREAD

**Issue by noliar** [sailro/Reflexil#71]
About Reflexil for ILSpy.

ILSpy Version: Latest Stable Version(2.4.0.1963)
Reflexil: Latest Nightly Version(Build 41 in AppVeyor)

It will throw NullReferenceException sometimes, when I click to see a Generic Type.

![qq 20160705140040](https://cloud.githubusercontent.com/assets/5773982/16575242/34a7c2b4-42b9-11e6-9865-e4611e1a610d.png)

**Comment by sailro** [comment]
A full repro would be perfect :)

"Sometimes" is an hard thing to debug.

**Comment by noliar** [comment]
@sailro 

e.g.
[aliyun_ram_net_sdk_2.0.7.zip](https://github.com/sailro/Reflexil/files/358564/aliyun_ram_net_sdk_2.0.7.zip)

I open 'aliyun-net-sdk-core.dll' in ILSpy.
![1](http://im2.ezgif.com/tmp/ezgif-1759553157.gif)
1. Click 'RpcAcsRequest'. Everything goes well.
![image](https://cloud.githubusercontent.com/assets/5773982/16756269/aca2dbbe-4836-11e6-921c-dfb777f34903.png)
2. Click others. It'll throws `NullReferenceException`.
![image](https://cloud.githubusercontent.com/assets/5773982/16756318/e7d9b6bc-4836-11e6-944c-82a11c4d634d.png)

**Comment by UlyssesWu** [comment]
Tested on Reflector and JD with Reflexil 2.0, both have the same exception. 
When switched to Reflexil 1.9 in Reflector, no error occurs.
So, it might be a bug of Reflexil 2.0.

**Comment by sailro** [comment]
Ok thanks, I will investigate

**Comment by sailro** [comment]
Fixed in 8bc19c04c1237ea689873530235bfe0d16020bce
