### ISSUE TITLE
Needs update or is it just me?

### ISSUE THREAD

**Issue by hugerichman** [sailro/Reflexil#72]
ILSpy just updated and I have no clue what this means but every time I try to Right click and press "Update ILSpy object model," it comes up with this error;
![halp](https://cloud.githubusercontent.com/assets/5052864/16653018/262a3ae6-4403-11e6-9697-c10891691ca5.PNG)

**Comment by sailro** [comment]
Hello, yes this is fixed in the master.

You can download the build here:
https://ci.appveyor.com/project/sailro/reflexil/build/artifacts

I have to release a new stable version :)

**Comment by hugerichman** [comment]
Thanks!
I figured it was that it needed an update because I used the previous version and it worked jusy fine.
