### ISSUE TITLE
Maybe it is possible to improve the feature "Replace all with code"?

### ISSUE THREAD

**Issue by qnnnnez** [sailro/Reflexil#73]
Maybe we can just create a subclass of the class who has the method we want to replace, and write the new method there.
Doing so, ancestors classes are accessable and we do not need stub fields anymore!

**Comment by sailro** [comment]
The whole process is made in a separate assembly. So lots of restrictions will apply: visibility for ancestors, the fact that the method has to be virtual.

But it's perhaps already possible, did you try to inherit from the code editor window ?

**Comment by qnnnnez** [comment]
Well, I haven't tried it myself.
But ```((AncestorClass)(object)this).AncestorMethod()``` works fine for me.

**Comment by qnnnnez** [comment]
I tried, and I think it is not possible yet. I changed the name of the class to avoid name conflict, and I compiled the code, but then no instruction appeared.
To do this, a patched temporary assembly may be necessary.
