### ISSUE TITLE
bug at creating new instruction

### ISSUE THREAD

**Issue by reverser69** [sailro/Reflexil#75]
hi
i cant creat a new call.the function exists but reflexil doesnt find it.
file attached.
![x](https://cloud.githubusercontent.com/assets/15833504/16879677/dfa70f2a-4ac6-11e6-89f6-868b0125a87e.PNG)

**Comment by reverser69** [comment]
it would be nice to have a possiblity to duplicate code lines.

**Comment by sailro** [comment]
Everything is fixed in the nightly build:
https://ci.appveyor.com/project/sailro/reflexil/build/artifacts

op_* support and you can copy/paste instructions

**Comment by sailro** [comment]
See #59

**Comment by reverser69** [comment]
thanks man.
this project is awesome,just awesome.
