### ISSUE TITLE
Assembly reference injection does not works in JustDecompile

### ISSUE THREAD

**Issue by goldenbr0wn** [sailro/Reflexil#77]
It works well in .NET Reflector but I still have a yellow 'beware' icon  in JustDecompile even though I located the assembly, using right click on the assembly ==> locate assembly.

**Comment by sailro** [comment]
Yes, the port made by the JustDecompile team is not feature complete.

On my side, I restarted from scratch for making my own JD plugin (in the justdecompile branch of this repo), but I have to work on this :)
