### ISSUE TITLE
[Question] Error CS1073 using reflexil, mscore dll referenced twice

### ISSUE THREAD

**Issue by goldenbr0wn** [sailro/Reflexil#79]
I am trying to inject a method in a DLL of a Unity 3D game. I am using the "replace all with code" feature but every time I am trying to compile I have the same error saying that the mscore assembly is referenced twice, though I haven't modified the game for now. I have tried to change the extension of mscore.dll in the unmanaged folder to something else but I always have the same error. I know I am not the first to encounter this issue but I have followed recommendations on other issues/thread without success for now. Any idea how to solve this?

**Comment by ElementalVenom** [comment]
Bottom of the replace all with code screen, there's a drop down box that has mscore 2.0 or something like that. Click it and then select Unity/Silverlight.

**Comment by sailro** [comment]
Yes you should use the Unity/Silverlight profile, but it should be selected by default when working with Unity assemblies.

**Comment by ElementalVenom** [comment]
Its not assigned by default in my experience.

**Comment by AntonProkofyev** [comment]
Hi i got this issue too. is it not fixed yet? is there any way to avoid it?
