### ISSUE TITLE
Suggestion: add search function on reflexil's instruction tab

### ISSUE THREAD

**Issue by yaminorito** [sailro/Reflexil#8]
Hello, 

First of all, reflexil is a really really big help as it is already, thank you very much.
It might be a good idea to add a search function on reflexil's instruction tab.
The function will search the text already in the cells of the table as it is shown, and then jump to that cell. As it is, searching for a specific line of code of CIL is like looking for a needle in a hay stack.
There is the "Replace all with code..." function, in which one can copy the decompiled code, modify it, then paste it on the "Replace all with code..." window, but not everything can be done with that indirect method in my own inexperience.
I'm just new in using reflexil, but as a new user of reflexil, this will be a really big help.

**Comment by sailro** [comment]
One easy way to do this is to have an IL view in the host program (like ILSpy or Reflector) and use the search feature. You have the IL Offset so you can easily seek the proper line in Reflexil.

![image](https://cloud.githubusercontent.com/assets/638167/5758394/9f6bdb76-9cc5-11e4-84ab-5af6ec99aff8.png)

**Comment by yaminorito** [comment]
I see! I will definitely try this. Thanks so much!
