### ISSUE TITLE
Reflexil isnt showing up in ILSpy

### ISSUE THREAD

**Issue by ElementalVenom** [sailro/Reflexil#81]
So its been forever since I updated ILSpy but i'm sorta sure i did this correctly but there's a high chance its wrong. Anyway so what i did was download ILSpy binaries into a folder and it ran fine. Then i downloaded the reflexil ILSpy plugin and put it into the same folder as the ILSpy binaries. Replacing files when asked. Now ILSpy still runs but reflexil isn't showing up. Whats wrong here??

**Comment by sailro** [comment]
Try with the latest:
https://ci.appveyor.com/project/sailro/reflexil/build/artifacts

They broke the API surface in the last release.
