### ISSUE TITLE
No match for field System.Timers.ElapsedEventHandler <>9__CachedAnonymousMethodDelegate1 in source assembly

### ISSUE THREAD

**Issue by gholol** [sailro/Reflexil#83]
I'm trying to overwrite a method with this code.
                
                using System.Timers;
                // etc blah blah
		ATOR()
		{
			Timer tm = new Timer();
			tm.Elapsed += delegate {
				//
			};
			tm.Interval = 2000;
			tm.Enabled = true;
		}

It fails. Is there a bug with reflexil?

**Comment by sailro** [comment]
It is not currently supported, you can only make changes impacting this method. Using this delegate construction rely on additional types/methods in the declaring type (created by the compiler). 

But you should be able to achieve what you want by injecting a new method first with the proper signature then use it to subscribe to "Elapsed" event.

**Comment by gholol** [comment]
Yeah, that worked, thank you
