### ISSUE TITLE
"Replace all with code..." try to replace another method with similar name

### ISSUE THREAD

**Issue by rexcanedo** [sailro/Reflexil#88]
![dos](https://cloud.githubusercontent.com/assets/22972129/19585622/04031c8c-971c-11e6-8cce-832c9afcb512.png)
![uno](https://cloud.githubusercontent.com/assets/22972129/19585623/0408f2b0-971c-11e6-93ce-c4f2e02d4a56.png)

Hello there, when i select a method with "replace all with code" it opens another method with similar  name as you can see in screenshots attached, i try it in v2 and v2.1 with same result, assembly is not obfuscated , method with similar name is the next one that is selected in the treeview of reflector.

**Comment by sailro** [comment]
Could you give me access to the assembly?

**Comment by rexcanedo** [comment]
Sure, here is it.


-------- Original Message --------
Subject: Re: [sailro/Reflexil] "Replace all with code..." try to replace
another method with similar name (#88)

**Comment by rexcanedo** [comment]
Did you get the assembly?, could you replicate this issue?

**Comment by sailro** [comment]
Nope. Please resend using my email address: sebastien[at]lebreton[dot]fr

I will have a look to see what's wrong.
Thanks

**Comment by sailro** [comment]
Fixed. This was a super bad luck in your case: to happen it needed both methods to have the exact same signature, declaring type and instruction count. Reflector-only bug.

A fixed build should be available here:
https://ci.appveyor.com/project/sailro/reflexil/build/artifacts

**Comment by rexcanedo** [comment]
it works now, Great job thanks.
