### ISSUE TITLE
The name 'Application' does not exist in the current context

### ISSUE THREAD

**Issue by ankilla** [sailro/Reflexil#9]
Hi,
 
I was editing 'Assembly-CSharp.dll' of a .unity3d game, injected class and created a function while adding code to that function I am getting error when mentioned as
code:
string _absoluteURL = Application.get_absoluteURL();
when compiled below error:
'The name 'Application' does not exist in the current context'
 
Pls tell me how to resolve this

**Comment by sailro** [comment]
I think that you just have to import UnityEngine namespace.

**Comment by ankilla** [comment]
how to import UnityEngine namespace.
I tried 
using UnityEngine;
then also giving the same error
