### ISSUE TITLE
Error CS1061 about not contain a definition

### ISSUE THREAD

**Issue by niznet** [sailro/Reflexil#90]
i compile with replace all code and received 1 error, this can be fixed?
Using ILSpy and .net Reflector

log:
'Wars_ShipControls' does not contain a definition for 'dialogue' and no extension method 'dialogue' accepting a first argument of type 'Wars_ShipControls' could be found (are you missing a using directive or an assembly reference?)

**Comment by sailro** [comment]
You have to check the scope of "dialogue" and "Wars_ShipControls". The whole injection process is not exactly what you could expect when really writing your app: the compilation is made in a separate and temporary assembly. 

So change scope of both to public, save your assembly/reload and retry to do the injection.
