### ISSUE TITLE
.NET Compact Framework 3.5 and 2.0 applications are not supported

### ISSUE THREAD

**Issue by dariox86** [sailro/Reflexil#95]
Editing executables and libraries built with Compact framework is not supported. Editing said programs throws an unsupported version message box. Feel free to comment if you need further evidence on the issue.

**Comment by sailro** [comment]
Sure could you give more details. What were you doing, what was the exact error message.
Thanks

**Comment by dariox86** [comment]
It's easy to reproduce. Just build the default .NET Compact Framework 2.0 or 3.5 GUI project in Visual Studio 2005 or 2008 and load the executable in ILSpy or .NET Reflector with Reflexil installed. Saving the executable, even in unmodified form, produces the output that you can see in the screenshot. Reflexil has a compatibility issue with .NET Compact applications. For the matter, it won't work with every .NET Compact application or library.
![immagine](https://cloud.githubusercontent.com/assets/7864785/23176468/636c31b0-f863-11e6-99f8-e28f29c95d9d.png)

**Comment by sailro** [comment]
Seems to be solved with the bump to Mono.Cecil 0.10.
I tried with a bunch of assemblies (CF 2 and 3.5), and was able to save files without issue.

See:
https://ci.appveyor.com/project/sailro/reflexil/build/artifacts
