### ISSUE TITLE
Injecting code doesn't seem to work

### ISSUE THREAD

**Issue by huckleberrypie** [sailro/Reflexil#97]
Been trying to paste this code to an existing Android Unity game's assembly in order to add immersive support to no avail:
https://forum.unity3d.com/threads/android-immersive-mode-c-only.298760/

Regardless of what I use, e.g. .NET Reflector, ILSpy or Telerik, adding the code in the link through "Replace all with code" results in the code not being added, without even an error message. This is right after I renamed mscorlib in order to get rid of those dependency messages I get with it.

**Comment by UlyssesWu** [comment]
I hope you do remember to remove `#if UNITY_ANDROID` and `#endif`.

**Comment by huckleberrypie** [comment]
Just those lines and nothing else?

**Comment by huckleberrypie** [comment]
Alright, got it, it seems to be working 'swell now! :D
