### ISSUE TITLE
An assembly with the same identity

### ISSUE THREAD

**Issue by Daisyuki** [sailro/Reflexil#98]
when i try to compile the code of anything in a certain .dll file it gives me this error:
An assembly with the same identity 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' has already been imported. Try removing one of the duplicate references.

any help?
![image](https://cloud.githubusercontent.com/assets/27167624/25314196/7c171ee6-27fc-11e7-8beb-782e943f88c0.png)

**Comment by Daisyuki** [comment]
and if your thinking its from me not writing any code, it's not.
it always happens.

**Comment by sailro** [comment]
Could you send us the dll ?

**Comment by sailro** [comment]
As this is a Unity dll, you just need to load the system.dll and mscorlib.dll from the game in your host program
